### ISSUE TITLE
[FEATURES] support for arm64 docker images

### ISSUE THREAD

**Issue by Iced-Sun** [juicedata/juicefs-csi-driver#205] opened 2021-11-28 13:36 UTC
**What feature you'd like to add:**

Support for arm64 docker images

**Why is this feature needed:**

With juicefs-csi-driver becoming part of the kubernetes ecosystem, it would be helpful to support arm64 docker images.

**Comment by zwwhdls** [comment] 2021-11-29 02:34
Duplicate of https://github.com/juicedata/juicefs-csi-driver/issues/99, closing

**Closed as completed by zwwhdls** 2021-11-29 02:34 UTC

**Comment by zwwhdls** [comment] 2021-12-01 07:28
Hi @Iced-Sun , arm64 image is supported now. You can use nightly image to have a try. arm64 image will also be supported in next release (after v0.11.0).
